spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: mservicet
      port: $MONGODB_SERVICE_INTERNAL_DEV_PORT

server:
  servlet:
    context-path: /mservicet
  port: 5000
